// <auto-generated />
using System;
using Image_upload.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Image_upload.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Image_upload.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Gener")
                        .HasColumnType("int");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RealeaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Gener = 6,
                            Length = "3hr",
                            PhotoPath = "Avengers.jpg",
                            RealeaseDate = new DateTime(2020, 1, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Avengers End Game"
                        },
                        new
                        {
                            MovieId = 2,
                            Gener = 6,
                            Length = "3hr 30min",
                            PhotoPath = "The Irishman.jpg",
                            RealeaseDate = new DateTime(2020, 1, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "The Irishman"
                        },
                        new
                        {
                            MovieId = 3,
                            Gener = 3,
                            Length = "2hr 22min",
                            PhotoPath = "Star wars.jpg",
                            RealeaseDate = new DateTime(2020, 1, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Star Wars: The Rise of Skywalker"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
